language: python
python:
  - 3.6
  - 3.7
  - 3.8
before_install:
  - sudo apt-get update
  - sudo apt-get -y install libfuse3-3 libsqlcipher0
install:
  - pip install pyfuse3
script:
  - python setup.py test
